// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop.Server.Data;

#nullable disable

namespace shop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("shop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "987654321",
                            ImageUrl = "https://cattalesinc.org/wp-content/uploads/slider2/DSC_0029-2048x1360.jpeg",
                            Price = 10.0m,
                            Title = "rubiks"
                        },
                        new
                        {
                            Id = 2,
                            Description = "123456789",
                            ImageUrl = "https://cattalesinc.org/wp-content/uploads/slider2/DSC_0029-2048x1360.jpeg",
                            Price = 100.0m,
                            Title = "kubiks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "147852369",
                            ImageUrl = "https://cattalesinc.org/wp-content/uploads/slider2/DSC_0029-2048x1360.jpeg",
                            Price = 75.0m,
                            Title = "rubiks kubiks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
